baseURL = '/'
languageCode = 'en-us'
title = 'Test site for mod-fontawesome'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[params.modules.fontawesome]
  mode = "symbols"    # Rendering mode: "symbols" | "svg" | "webfonts"
  debug = true
  skipMissing = false

[module]
  # Build and serve using local mod-fontawesome clone declared in the named Hugo workspace:
  workspace = "mod-fontawesome.work"
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome/v4"
